export const NFTData = [
  {
    img: "/images/nfts/Cherkasy.jpg",
    link: "",
    title: "Cherkasy",
    name: "Blue Palace",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Chernihiv.jpg",
    link: "",
    title: "Chernihiv",
    name: "Saviour-Transfiguration Cathedral",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Chernivtsi.jpg",
    link: "",
    title: "Chernivtsi",
    name: "Yuriy Fedkovych Chernivtsi National University",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Crimea.jpg",
    link: "",
    title: "Crimea",
    name: "The Swallow's Nest Castle",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Dnipro.jpg",
    link: "",
    title: "Dnipro",
    name: "Menorah center",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Donetsk.jpg",
    link: "",
    title: "Donetsk",
    name: "Donbass Arena Stadium",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Ivano-Frankivsk.jpg",
    link: "",
    title: "Ivano Frankivsk",
    name: "Ratusha (The City Hall Building)",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Kharkiv.jpg",
    link: "",
    title: "Kharkiv",
    name: "Annunciation Cathedral",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Kherson.jpg",
    link: "",
    title: "Kherson",
    name: "Monument to prince Grigory Potemkin-Tavricheski",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Khmelnytskyi.jpg",
    link: "",
    title: "Khmelnytskyi",
    name: "Kamianets-Podilskyi Castle",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Kropyvnytskyi.jpg",
    link: "",
    title: "Kropyvnytskyi",
    name: "Ukraine Guardian Angel",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Kyiv.jpg",
    link: "",
    title: "Kyiv",
    name: "“Ladya” monument to the founders of Kyiv",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Luhansk.jpg",
    link: "",
    title: "Luhansk",
    name: "City History and Culture Museum",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Lutsk.jpg",
    link: "",
    title: "Lutsk",
    name: "Lubart's Castle",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Lviv.jpg",
    link: "",
    title: "Lviv",
    name: "Latin Cathedral",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Mykolaiv.jpg",
    link: "",
    title: "Mykolaiv",
    name: "Mykolaiv Astronomical Observatory",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Odesa.jpg",
    link: "",
    title: "Odesa",
    name: "Odesa National Academic Theatre of Opera and Ballet",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Poltava.jpg",
    link: "",
    title: "Poltava",
    name: "former Noble and Peasant Land Bank",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Rivne.jpg",
    link: "",
    title: "Rivne",
    name: "The Hall of Chamber and Organ Music",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Sumy.jpg",
    link: "",
    title: "Sumy",
    name: "Holy Resurrection Cathedral",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Ternopil.jpg",
    link: "",
    title: "Ternopil",
    name: "Cathedral of the Immaculate Conception of the Blessed Virgin Mary",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Uzhgorod.jpg",
    link: "",
    title: "Uzhgorod",
    name: "Uzhgorod Castle",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Vinnytsia.jpg",
    link: "",
    title: "Vinnytsia",
    name: "Vinnytsia water tower",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Zaporizhzhia.jpg",
    link: "",
    title: "Zaporizhzhia",
    name: "Church of the Intercession, Khortytsia island",
    amount: "$ 14.99",
  },
  {
    img: "/images/nfts/Zhytomyr.jpg",
    link: "",
    title: "Zhytomyr",
    name: "St. Michael Archangel Cathedral",
    amount: "$ 14.99",
  },
];
